package ch.isageek.tyderion.habittracker.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import ch.isageek.tyderion.habittracker.model.Habit;
import ch.isageek.tyderion.habittracker.model.Occurrence;

import ch.isageek.tyderion.habittracker.model.HabitDao;
import ch.isageek.tyderion.habittracker.model.OccurrenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig habitDaoConfig;
    private final DaoConfig occurrenceDaoConfig;

    private final HabitDao habitDao;
    private final OccurrenceDao occurrenceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        habitDaoConfig = daoConfigMap.get(HabitDao.class).clone();
        habitDaoConfig.initIdentityScope(type);
        occurrenceDaoConfig = daoConfigMap.get(OccurrenceDao.class).clone();
        occurrenceDaoConfig.initIdentityScope(type);
        habitDao = new HabitDao(habitDaoConfig, this);
        occurrenceDao = new OccurrenceDao(occurrenceDaoConfig, this);

        registerDao(Habit.class, habitDao);
        registerDao(Occurrence.class, occurrenceDao);
    }

    public void clear() {
        habitDaoConfig.getIdentityScope().clear();
        occurrenceDaoConfig.getIdentityScope().clear();
    }

    public void deleteAllData() {
        habitDao.deleteAll();
        occurrenceDao.deleteAll();
    }


    public HabitDao getHabitDao() {
        return habitDao;
    }
    public OccurrenceDao getOccurrenceDao() {
        return occurrenceDao;
    }
}
