package ch.isageek.tyderion.habittracker.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import ch.isageek.tyderion.habittracker.model.Habit;
import ch.isageek.tyderion.habittracker.model.Occurence;

import ch.isageek.tyderion.habittracker.model.HabitDao;
import ch.isageek.tyderion.habittracker.model.OccurenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig habitDaoConfig;
    private final DaoConfig occurenceDaoConfig;

    private final HabitDao habitDao;
    private final OccurenceDao occurenceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        habitDaoConfig = daoConfigMap.get(HabitDao.class).clone();
        habitDaoConfig.initIdentityScope(type);
        occurenceDaoConfig = daoConfigMap.get(OccurenceDao.class).clone();
        occurenceDaoConfig.initIdentityScope(type);
        habitDao = new HabitDao(habitDaoConfig, this);
        occurenceDao = new OccurenceDao(occurenceDaoConfig, this);

        registerDao(Habit.class, habitDao);
        registerDao(Occurence.class, occurenceDao);
    }

    public void clear() {
        habitDaoConfig.getIdentityScope().clear();
        occurenceDaoConfig.getIdentityScope().clear();
    }

    public void deleteAllData() {
        habitDao.deleteAll();
        occurenceDao.deleteAll();
    }


    public HabitDao getHabitDao() {
        return habitDao;
    }
    public OccurenceDao getOccurenceDao() {
        return occurenceDao;
    }
}
