package ch.isageek.tyderion.habittracker.model;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.util.Log;

import java.util.UUID;
// KEEP INCLUDES END
/**
 * Entity mapped to table HABIT.
 */
public class Habit extends HabitBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public Habit() {
    }

    public Habit(Long id) {
        super(id);
    }

    public Habit(Long id, java.util.Date dateCreated, String name, Boolean isPositive, String description, String uuid) {
        super(id, dateCreated, name, isPositive, description, uuid);
    }

    // KEEP METHODS - put your custom methods here


    public Habit(Long id, java.util.Date dateCreated, String name, Boolean isPositive, String description) {
        super(id, dateCreated, name, isPositive, description, "");
    }
    @Override
    public void onBeforeSave() {
        super.onBeforeSave();
        if (this.uuid == null || this.uuid.length() != 36) {
            this.uuid = UUID.randomUUID().toString();
        }
    }
    // KEEP METHODS END

}
