package ch.isageek.tyderion.habittracker.model;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HABIT.
 */
public class Habit extends HabitBase  {
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    public Habit() {
    }

    public Habit(Long id) {
        super(id);
    }

    public Habit(Long id, java.util.Date dateCreated, String name, Boolean isPositive) {
        super(id, dateCreated, name, isPositive);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
