package ch.isageek.tyderion.habittracker.model;






// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table HABIT.
 */
abstract public class HabitBase {

    protected Long id;
    protected java.util.Date dateCreated;
    protected String name;
    protected Boolean isPositive;
    protected String description;




    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HabitBase() {
    }

    public HabitBase(Long id) {
        this.id = id;
    }

    public HabitBase(Long id, java.util.Date dateCreated, String name, Boolean isPositive, String description) {
        this.id = id;
        this.dateCreated = dateCreated;
        this.name = name;
        this.isPositive = isPositive;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(java.util.Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsPositive() {
        return isPositive;
    }

    public void setIsPositive(Boolean isPositive) {
        this.isPositive = isPositive;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void updateNotNull(Habit other) {
        if(this == other) {
            return;//both came from db, no need to run this.
        }

        if(other.id != null) {
            this.id = other.id;
        }


        if(other.dateCreated != null) {
            this.dateCreated = other.dateCreated;
        }


        if(other.name != null) {
            this.name = other.name;
        }


        if(other.isPositive != null) {
            this.isPositive = other.isPositive;
        }


        if(other.description != null) {
            this.description = other.description;
        }

        // relationships
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public void onBeforeSave() {
        //you can override this method and do some stuff if you want to :)

    }
}
