package ch.isageek.tyderion.habittracker.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import ch.isageek.tyderion.habittracker.model.Occurrence;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table OCCURRENCE.
*/
public class OccurrenceDao extends AbstractDao<Occurrence, Long> {

    public static final String TABLENAME = "OCCURRENCE";

    /**
     * Properties of entity Occurrence.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id =new Property(0, Long.class , "id", true, "_id");
        public final static Property Date =new Property(1, java.util.Date.class , "date", false, "DATE");
        public final static Property HabitID =new Property(2, Long.class , "habitID", false, "HABIT_ID");
    };

    private DaoSession daoSession;

    private Query<Occurrence> habit_OccurrenceListQuery;

    public OccurrenceDao(DaoConfig config) {
        super(config);
    }

    public OccurrenceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OCCURRENCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DATE' INTEGER," + // 1: date
                "'HABIT_ID' INTEGER);"); // 2: habitID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OCCURRENCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Occurrence entity) {
        stmt.clearBindings();
        entity.onBeforeSave();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);

        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());

        }
 
        Long habitID = entity.getHabitID();
        if (habitID != null) {
            stmt.bindLong(3, habitID);

        }
    }

    @Override
    protected void attachEntity(Occurrence entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public Occurrence readEntity(Cursor cursor, int offset) {
        Occurrence entity = new Occurrence( //

            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) , // id
            cursor.isNull(offset + 1) ? null : new java.util.Date( cursor.getLong(offset + 1) ) , // date
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // habitID
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Occurrence entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) );
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date( cursor.getLong(offset + 1) ) );
        entity.setHabitID(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) );
     }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Occurrence entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(Occurrence entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /** Internal query to resolve the "occurrenceList" to-many relationship of Habit. */
    public synchronized List<Occurrence> _queryHabit_OccurrenceList(Long habitID) {
        if (habit_OccurrenceListQuery == null) {
            QueryBuilder<Occurrence> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.HabitID.eq(habitID));
            queryBuilder.orderRaw("DATE DESC");
            habit_OccurrenceListQuery = queryBuilder.build();
        } else {
            habit_OccurrenceListQuery.setParameter(0, habitID);
        }
        return habit_OccurrenceListQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getHabitDao().getAllColumns());
            builder.append(" FROM OCCURRENCE T");
            builder.append(" LEFT JOIN HABIT T0 ON T.'HABIT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Occurrence loadCurrentDeep(Cursor cursor, boolean lock) {
        Occurrence entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Habit habit = loadCurrentOther(daoSession.getHabitDao(), cursor, offset);
        entity.setHabit(habit);

        return entity;    
    }

    public Occurrence loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Occurrence> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Occurrence> list = new ArrayList<Occurrence>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Occurrence> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Occurrence> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
