package ch.isageek.tyderion.habittracker.model;



// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.text.SimpleDateFormat;
// KEEP INCLUDES END
/**
 * Entity mapped to table OCCURENCE.
 */
public class Occurence extends OccurenceBase  {
    // KEEP FIELDS - put your custom fields here
    private static SimpleDateFormat dateFormatter = new SimpleDateFormat("dd.MM.yyyy hh:mm:ss");
    // KEEP FIELDS END
    public Occurence() {
    }

    public Occurence(Long id) {
        super(id);
    }

    public Occurence(Long id, java.util.Date date, Long habitID) {
        super(id, date, habitID);
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "Occurrence: " + Occurence.dateFormatter.format(this.date);
    }
    // KEEP METHODS END

}
